name: flutter_blue_plus
description: Flutter plugin for connecting and communicating with Bluetooth Low Energy devices.
version: 2.0.0
homepage: https://github.com/chipweinberger/flutter_blue_plus

environment:
  sdk: ^3.0.0
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  # use specific versions. 
  #  - users otherwise forget to update all
  #  - simpler bug reporting
  #  - unified changelog
  #  - users can still manually override
  flutter_blue_plus_platform_interface:
    git:
      url: https://github.com/Vineet-0101/flutter_blue_plus.git
      path: packages/flutter_blue_plus_platform_interface
  flutter_blue_plus_android:
    git:
      url: https://github.com/Vineet-0101/flutter_blue_plus.git
      path: packages/flutter_blue_plus_android
  flutter_blue_plus_darwin:
    git:
      url: https://github.com/Vineet-0101/flutter_blue_plus.git
      path: packages/flutter_blue_plus_darwin
  flutter_blue_plus_linux:
      git:
      url: https://github.com/Vineet-0101/flutter_blue_plus.git
      path: packages/flutter_blue_plus_linux
  flutter_blue_plus_web:    
    git:
      url: https://github.com/Vineet-0101/flutter_blue_plus.git
      path: packages/flutter_blue_plus_web

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_blue_plus_android
      ios:
        default_package: flutter_blue_plus_darwin
      linux:
        default_package: flutter_blue_plus_linux
      macos:
        default_package: flutter_blue_plus_darwin
      web:
        default_package: flutter_blue_plus_web
