name: flutter_blue_plus_linux
description: Linux implementation of the flutter_blue_plus plugin.
version: 8.0.0
homepage: https://github.com/Vineet-0101/flutter_blue_plus

environment:
  sdk: ^3.0.0
  flutter: '>=3.7.0'

dependencies:
  bluez: '>=0.7.8 <0.9.0'
  flutter:
    sdk: flutter
  flutter_blue_plus_platform_interface:
    git:
      url: https://github.com/Vineet-0101/flutter_blue_plus.git
      path: packages/flutter_blue_plus_platform_interface
  rxdart: '>=0.27.0 <0.29.0'

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: flutter_blue_plus
    platforms:
      linux:
        dartPluginClass: FlutterBluePlusLinux
